Initial submission
slack-samples/deno-triage-bot pull request #1
Opened 2023-10-12 23:57 UTC by yli919

### Type of change (place an x in the [ ] that applies)

- [x] New sample
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation

### Summary

This PR introduces a new sample app for Run-on-Slack using the deno-slack-sdk, the Triage Bot app. Triage Bot can generate reports for support requests in Slack public channels. In addition, users can configure channels to receive reports on a scheduled basis.

To test this you can run slack create -t slack-samples/deno-triage-bot sample-submission and then follow along the instructions in the README.

### Requirements (place an x in each [ ] that applies)

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

2023-10-16 15:55 UTC, filmaj requested changes
Wow this is great work!

I gave these workflows a shot and here's some generic feedback:

- when I installed to my relatively-untouched production workspace, the emoji `:blue-circle:` doesn't exist, so doesn't render as an emoji. `:large-blue-circle:`, however, does exist. Maybe we should make sure to use only default workspace emojis?
- I was confused by what the Configure Triagebot questions were asking:
  - what does 'lookback' mean in the context of this app? Is it only for reporting? I was confused by this. Maybe we should expand on define the term, esp. in the configuration modal views? Maybe we could provide some hint text for what this means?
  - "What cron schedule should messages be posted to the channel?" I also didn't understand. Is triagebot posting messages to the channel? As someone new to the bot, it wasn't clear to me what this was asking. Perhaps we could clarify that too.

I also encountered an error trying to run the "Triage by Days" shortcut workflow (left this comment in-line).

2023-10-16 15:55 UTC, filmaj commented on functions/triage_by_days.ts
> +      // get webhook trigger for private report from datastore
When I tried to trip the 'Triage by Lookback Days' shortcut trigger, I got an error here. I did not configure a webhook at all, though. Maybe that is related, as this code is looking for a webhook.

```
2023-10-16 11:53:01 [info] [Fn060X08FZN3] (Trace=Tr061Q8E1T4Z) Function 'Triage by lookback days' (app function) started
error: Uncaught (in promise) TypeError: Invalid URL: 'undefined'
const resp = await fetch(url, {
                     ^
at getSerialization (ext:deno_url/00_url.js:89:11)
at new URL (ext:deno_url/00_url.js:380:27)
at new Request (ext:deno_fetch/23_request.js:304:25)
at ext:deno_fetch/26_fetch.js:432:27
at new Promise (<anonymous>)
at fetch (ext:deno_fetch/26_fetch.js:428:18)
at tripPrivateReportWebhookTrigger (file:///Users/fmaj/src/deno-triage-bot/functions/triage_by_days.ts:91:22)
at file:///Users/fmaj/src/deno-triage-bot/functions/triage_by_days.ts:64:13
at eventLoopTick (ext:core/01_core.js:183:11)
at async ViewRouter.viewSubmission (https://deno.land/x/deno_slack_sdk@2.4.0/functions/interactivity/view_router.ts:174:12)
Getting webhook private from the datastore...
Tripping trigger to post in channel C061BG61H5Y to U02AEHE4KG9 with url undefined}
```

2023-10-16 17:16 UTC, yli919 commented
> Wow this is great work!
> 
> I gave these workflows a shot and here's some generic feedback:
> 
> * when I installed to my relatively-untouched production workspace, the emoji `:blue-circle:` doesn't exist, so doesn't render as an emoji. `:large-blue-circle:`, however, does exist. Maybe we should make sure to use only default workspace emojis?
> * I was confused by what the Configure Triagebot questions were asking:
>   
>   * what does 'lookback' mean in the context of this app? Is it only for reporting? I was confused by this. Maybe we should expand on define the term, esp. in the configuration modal views? Maybe we could provide some hint text for what this means?
>   * "What cron schedule should messages be posted to the channel?" I also didn't understand. Is triagebot posting messages to the channel? As someone new to the bot, it wasn't clear to me what this was asking. Perhaps we could clarify that too.
> 
> I also encountered an error trying to run the "Triage by Days" shortcut workflow (left this comment in-line).

Thanks for the review! I will change the list of emojis to only include default emojis in the messages, I think it's a great call out. Lookback means the days that triagebot will look back to find triage requests, and cron schedule defines the schedule that triagebot will post to the channel configured which follows the [cron format](https://crontab.guru). I do understand why new users may be confused and can add a bit more context to what it's asking.

2023-10-16 17:21 UTC, yli919 commented on functions/triage_by_days.ts
> +      // get webhook trigger for private report from datastore
>  I did not configure a webhook at all, though.
Yeah I think you are seeing this error exactly because of the missing webhook trigger url. In order for the `triage by lookback days` and scheduled posts to work, the users have to create the following webhook triggers and put their urls into the datastores:
- triggers/private_report_webhook_trigger.ts
- triggers/public_report_webhook_trigger.ts

```
$ slack datastore put '{"datastore": "webhook", "app": "app_id", "item": {"name": "private", "url": "triagebot private report webhook url"}}'

$ slack datastore put '{"datastore": "webhook", "app": "app_id", "item": {"name": "public", "url": "triagebot public report webhook url"}}'
```
These steps are included in the readme but I guess they can be hard to find. Should I change the structure of the readme to include the info higher up?

2023-10-16 19:25 UTC, filmaj commented on functions/triage_by_days.ts
> +      // get webhook trigger for private report from datastore
Yes I think so. If there are dependencies between the workflows, we should make that clear up front.
Even better: are the webhook URLs required to run this particular workflow? Conceptually, should we be coupling the two workflows together this way?

2023-10-31 17:51 UTC, yli919 commented
I think I've changed the readme and the workflow parameters based on the feedback. Would you like to give this another review @filmaj? 🙇‍♀️

2023-11-01 13:35 UTC, filmaj approved these changes
LGTM!

2023-11-03 17:40 UTC, misscoded approved these changes
Thank you for taking on the creation of this sample, @yli919! 🙇🏼‍♀️ 

There are some minor adjustments that we'll make down the road to code style, comments, and the README, but there's nothing here that you need to worry about prior to merge.

2023-11-03 17:40 UTC, merged